# Port de l'application
server.port=${PORT:8085}

# Configuration MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/shopflow_db?createDatabaseIfNotExist=true&useSSL=false}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.jpa.properties.hibernate.format_sql=true


# === Swagger ===
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.packages-to-scan=com.shopflow.main.controller
# === JWT ===
jwt.secret=shopflow-super-secret-key-that-is-at-least-32-chars-long-!
jwt.access-token-expiration-ms=900000
jwt.refresh-token-expiration-ms=604800000
